repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
  - repo: local
    hooks:
      - id: test
        name: Running tests
        always_run: true
        language: system
        require_serial: true
        stages: [push]
        entry: make test