[Icon Theme]
Name=Hicolor
Comment=Fallback icon theme
Hidden=true
Directories=16x16/apps,24x24/apps,scalable/apps,scalable/actions,scalable/categories,scalable/status

[16x16/apps]
Size=16
Context=Applications

[24x24/apps]
Size=24
Context=Applications

[scalable/apps]
Size=16
MaxSize=48
Type=Scalable
Context=Applications

[scalable/apps]
Size=16
MaxSize=48
Type=Scalable
Context=Applications

[scalable/actions]
Size=16
MaxSize=48
Type=Scalable
Context=Actions

[scalable/categories]
Size=16
MaxSize=48
Type=Scalable
Context=Categories

[scalable/status]
Size=16
MaxSize=48
Type=Scalable
Context=Status