name: lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch: 

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          activate-environment: true
          enable-cache: true

      - name: Set up Task
        uses: go-task/setup-task@v1

      - name: Create development environment
        run: uv venv --clear --system-site-packages --python python3 .venv

      - name: Sync development dependencies
        run: uv sync --group dev

      - name: Run static analysis
        run: task check
