name: lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch: 

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - uses: chartboost/ruff-action@v1