name: Lint Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request: 

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - uses: chartboost/ruff-action@v1