name: release

on:
  push:
    branches:
      - master
    paths:
      - 'data/**'
      - 'tomate/**'
      - 'setup.py'
      - '.bumpversion.cfg'

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Trigger build
        env:
          TOKEN: ${{ secrets.OBS_TOKEN }}
        run: make trigger-build