name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request: 
  workflow_dispatch: 

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: eliostvs/tomate

    steps:
      - uses: actions/checkout@v7

      - name: Create development environment
        run: task dev

      - name: Create mime database
        run: task mime

      - name: Test
        run: task test
