name: Test Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request: 

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: eliostvs/tomate
      volumes:
        - ${{ github.workspace }}:/code
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Create mime database
        run: |
          make mime
        
      - name: Test
        run: |
          make test